### ISSUE TITLE
I get an error when I try to download the Nuget package.

### ISSUE THREAD

**Issue by vector-man** [ailen0ada/xxHash4net#2]
I install using Visual Studio 2015 and I get this:

    Attempting to gather dependency information for package 'xxHash4net.1.1.1' with respect to project 'AsyncHashAlgorithm.Extensions.Data.xxHash4net', targeting '.NETFramework,Version=v4.6.2'
    Attempting to resolve dependencies for package 'xxHash4net.1.1.1' with DependencyBehavior 'Lowest'
    Resolving actions to install package 'xxHash4net.1.1.1'
    Resolved actions to install package 'xxHash4net.1.1.1'
      GET https://api.nuget.org/packages/xxhash4net.1.1.1.nupkg
      OK https://api.nuget.org/packages/xxhash4net.1.1.1.nupkg 35ms
    Installing xxHash4net 1.1.1.
    Error downloading 'xxHash4net.1.1.1' from 'https://api.nuget.org/packages/xxhash4net.1.1.1.nupkg'.
    Access to the path 'C:\Users\Michael\.nuget\packages\xxHash4net\1.1.1' is denied.
    Install failed. Rolling back...
    Package 'xxHash4net.1.1.1' does not exist in project 'AsyncHashAlgorithm.Extensions.Data.xxHash4net'
    Package 'xxHash4net.1.1.1' does not exist in folder 'C:\Users\Michael\Documents\Visual Studio 2015\Projects\Project1\packages'
    NuGet.Protocol.Core.Types.FatalProtocolException: Error downloading 'xxHash4net.1.1.1' from 'https://api.nuget.org/packages/xxhash4net.1.1.1.nupkg'. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Michael\.nuget\packages\xxHash4net\1.1.1' is denied.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at NuGet.Packaging.StreamExtensions.CopyToFile(Stream inputStream, String fileFullPath)
       at NuGet.Packaging.PackageFileExtractor.ExtractPackageFile(String source, String target, Stream stream)
       at NuGet.Packaging.PackageArchiveReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, CancellationToken token)
       at NuGet.Packaging.PackageExtractor.<>c__DisplayClass2_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__0`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Protocol.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Protocol.GetDownloadResultUtility.<>c__DisplayClass0_0.<<GetDownloadResultAsync>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Protocol.HttpSource.<ProcessStreamAsync>d__25`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Protocol.GetDownloadResultUtility.<GetDownloadResultAsync>d__0.MoveNext()
       --- End of inner exception stack trace ---
       at NuGet.Protocol.GetDownloadResultUtility.<GetDownloadResultAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
    ========== Finished ==========

**Comment by ailen0ada** [comment]
fixed in #3 . Thank you for your report!

**Comment by vector-man** [comment]
No problem! Thanks for the quick fix!. Oh, and great library by the way!

**Comment by ailen0ada** [comment]
Please don't hesitate to notify me when you've encountered problem!
